version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2909
      MYSQL_DATABASE: CarWashesDb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  carwashes_api:
    container_name: carwashapi
    build: . 
    restart: always
    ports:                
      - "5000:80"
volumes:
  mysql-data:
    